#/ Controller version = 3.14.01
#/ Date = 1/15/2025 5:34 PM
#/ User remarks = 
#1
!PNAME=
!PDESC=
INT AXIS_X =1
INT AXIS_Y =0


ENABLE AXIS_X
TILL   MST(AXIS_X).#ENABLED=1

HOME AXIS_X,1,50,,,50
TILL AST(AXIS_X).#INHOMING=0



ENABLE AXIS_Y
TILL   MST(AXIS_Y).#ENABLED=1

HOME AXIS_Y,1,50,,,50
TILL AST(AXIS_Y).#INHOMING=0


STOP 
#3
!PNAME=
!PDESC=
ENABLE(X,Y,Z)
int k=0

loop MyMatrixRowsCount
ptp/ev(X,Y,Z),MyMatrix(k)(0),MyMatrix(k)(1),MyMatrix(k)(2),ScanSpeed
TILL (MST(X).#MOVE=0)&(MST(Y).#MOVE=0)&(MST(Z).#MOVE=0)
if(Trigger0_0=1)
OUT(0).8=1
end
WAIT(WaitTime)
if(Trigger0_0=1)
OUT(0).8=0
end
k=k+1
end
ptp/ev(X,Y,Z),0,0,0,ScanSpeed
WAIT(WaitTime)
DISP "Over!"
TILL (MST(X).#MOVE=0)&(MST(Y).#MOVE=0)&(MST(Z).#MOVE=0)
STOP
#5
!PNAME=
!PDESC=
!PEG Routine generated by PEG Wizard
!	Generated for Unit: 0, P/N: ECMsm-4C00N-NNNNN, S/N: PSM71963
GLOBAL INT AXIS
AXIS = 0               
!=================================================================
DISABLE (AXIS)                ! Disable axis before setting params
VEL(AXIS) = 50                                     ! Set velocity
ACC(AXIS) = 10*VEL(AXIS)                        ! Set acceleration
DEC(AXIS) = 10*VEL(AXIS)                        ! Set deceleration
JERK(AXIS) = 100*VEL(AXIS)                              ! Set jerk
KDEC(AXIS) = 100*VEL(AXIS)                 ! Set kill deceleration


! Variable declaration and definition
int node_first_axis=0	! Unit's first axis (an axis used for identifying the unit)

! Triggers: Assign encoders to PEG engines
ASSIGNPEG node_first_axis,0x00000000,0b000

!Incremental PEG
!===============

! Variable declaration and definition
ENABLE (AXIS)                                        ! Enable axis

CYCLE:       
int PEG0_Engine=0			! PEG Engines
real PEG0_pulse_width=0.01		! Width of pulse (ms)
real PEG0_first_point=0		! First point for the PEG generation (User Units)
real PEG0_interval=2		! The distance between PEG events (User Units)
real PEG0_last_point=50		! Last point for PEG generation (User Units)

! Outputs: Assign PEG output signals to physical pins
ASSIGNPOUTS node_first_axis,8,0b0000	! Pulse, Encoder: 0, Connector/Pins: J11-I/O(21:PEG0+ 6:PEG0-)

! Incremental PEG activation
PEG_I/a PEG0_Engine,PEG0_pulse_width,PEG0_first_point,PEG0_interval,PEG0_last_point
!	(/a) - Prevernt Error Accumulation (Recommended)

! Wait until PEG is ready before executing motion
TILL AST(PEG0_Engine).#PEGREADY
PTP/E AXIS, 50                                       ! Move to 10
STOPPEG AXIS         ! Prevent PEG pulses firing on the 'way back'
PTP/E AXIS, 0                                          ! Move to 0
GOTO CYCLE                                        ! Repeat process
STOP


STOP
#A
!PNAME=
!PDESC=
!axisdef X=0,Y=1,Z=2,T=3,A=4,B=5,C=6,D=7
!axisdef x=0,y=1,z=2,t=3,a=4,b=5,c=6,d=7
global int I(100),I0,I1,I2,I3,I4,I5,I6,I7,I8,I9,I90,I91,I92,I93,I94,I95,I96,I97,I98,I99
global real V(100),V0,V1,V2,V3,V4,V5,V6,V7,V8,V9,V90,V91,V92,V93,V94,V95,V96,V97,V98,V99
AXISDEF X=0,Y=1,Z=2
GLOBAL real MyMatrix(25000)(3)
GLOBAL REAL arrZ(100)
GLOBAL REAL ScanSpeed
GLOBAL INT MyMatrixRowsCount,WaitTime,Trigger0_0,Trigger0_1
