;配置
[Config]
TotalAxis=4
AxisX=0
AxisY=1
AxisZ=2
AxisX_Dir=1
AxisY_Dir=-1
AxisZ_Dir=-1
ConfigText8=8
ConfigText9=9
ConfigText10=10
AppName=CISM运动控制-水浸超声采集成像系统
Abbreviation=HFOS
AppVer=5.0
CustomerLogoPath=001
CustomerName=哈尔滨工业大学
Manufacturer=北京辰阳
PrinterEnable=False
SpeechEnable=False
LoginEnable=False
RecipeEnable=False
ReviewEnable=False
OptionEnable=False
MaintainEnable=False
ToolsEnable=False
UserEnable=False
ConfigEnable=True
DebugEnable=False
DemoEnable=False

;设置
[Option]
PrinterName=Microsoft Print to PDF
FolderPath=E:\Unit\管理\模板\软件\TYI_STUDIO\300_模板\FlatUI_TestPlatform\bin\Debug\btformat\format.btw
AutoRecording=True
PosCylEn=False
DeviceNum=120
AddValueL=27
AddValueR=27
COM=2
Addr=1
IP=192.168.2.2
TagPrintEn=False
DataMode=1

OptionText3=3
OptionText4=4
OptionText5=5
OptionText6=6
OptionText7=7
OptionText8=8
OptionText9=9
OptionText10=10
;ACS软件参数
AxisUnitY=0
SpeedX=10
SpeedY=50
SpeedZ=20
TravelX=1
TravelY=1
TravelZ=1
PhotoPath=D:\pic
CutPicPath=D:\pic

;CCD参数
DrawLineColor=0
DrawLineWidth=1
DrawLineStyle=0
DisBetweenLine=10
DisFormCenterToLine=30
AngleJogDelayTime=0
AnglePosTarget=180
AnglePosSpeed=20

;临时记录
[Temp]
PosXOffset=-69.1655659675599
PosYOffset=-69.1655659675599
PosZOffset=0
Serial=00103
[DEBUG]
结果=1
