;配置
[Config]
TotalAxis=4
AxisX=0
AxisY=1
AxisZ=2
AxisX_Dir=1
AxisY_Dir=-1
AxisZ_Dir=-1
ConfigText8=8
ConfigText9=9
ConfigText10=10
AppName=叶片水浸超声扫描运动平台
Abbreviation=HFOS
AppVer=5.0
CustomerLogoPath=001
CustomerName=哈尔滨工业大学
Manufacturer=北京辰阳
PrinterEnable=False
SpeechEnable=False
LoginEnable=False
RecipeEnable=False
ReviewEnable=False
OptionEnable=False
MaintainEnable=False
ToolsEnable=False
UserEnable=False
ConfigEnable=True
DebugEnable=False
DemoEnable=False

;设置
[Option]
PrinterName=Microsoft Print to PDF
FolderPath=E:\Unit\管理\模板\软件\TYI_STUDIO\300_模板\FlatUI_TestPlatform\bin\Debug\btformat\format.btw
AutoRecording=True
PosCylEn=False
DeviceNum=120
AddValueL=27
AddValueR=27
COM=2
Addr=1
IP=192.168.2.2
TagPrintEn=False
DataMode=1

OptionText3=3
OptionText4=4
OptionText5=5
OptionText6=6
OptionText7=7
OptionText8=8
OptionText9=9
OptionText10=10
;ACS软件参数
AxisUnitY=0
SpeedX=50
SpeedY=50
SpeedZ=10
TravelX=1
TravelY=1
TravelZ=1
PhotoPath=D:\pic
CutPicPath=D:\pic

;CCD参数
DrawLineColor=0
DrawLineWidth=1
DrawLineStyle=0
DisBetweenLine=10
DisFormCenterToLine=30

;临时记录
[Temp]
PosXOffset=0
PosYOffset=0
PosZOffset=0
Serial=00103
[DEBUG]
结果=1

[DEFAULT]
DEFAULT_IP=11
DEFAULT_DEVICE=MINI
REFRESH_DISPLAY_PERIOD_IN_MS=100
REFRESH_DATACOM_DATA_PERIOD_IN_MS=1000
GATE_MODE_AMP=Maximum
GATE_MODE_TOF=AmplitudeDetection


[COLOR]
GATE1=0x00CCCC
GATE2=0x00CC00
GATE3=0x9933FF
GATE4=0xFF0000
CURSOR_AXIS=0xC0C0C0
CURSOR_NAME=0xC0C0C0
RULER_AXIS=0xC0C0C0
RULER_LABEL=0xC0C0C0
RULER_NAME=0xC0C0C0
ASCAN_BG_COLOR=0xFFFFFF
ASCAN_COLOR=0x0000FF

[ENCODERS]
;Encoder Type: 0: static scan, 1: quadrature, 2: quadrature 4 edges, 3: direction/count, 4: forward/backward, 5: speed measurement
ENC1_RESOLUTION=-1
ENC1_DIVIDER=-1
ENC1_TYPE=-1
ENC1_ENABLE=0
;Encoder wire pins: 1-8 for MIO (must be an input, 7-8 are usually output pins), 1-32 for PIO.
ENC1_WIREA=-1
ENC1_WIREB=-1
ENC2_RESOLUTION=-1
ENC2_DIVIDER=-1
ENC2_TYPE=-1
ENC2_ENABLE=0
ENC2_WIREA=-1
ENC2_WIREB=-1
TRIGGER_STEP=-1

[IO]
; possible values: Enc1A, Enc1B, Enc2A, Enc2B, SigCyc, SigSeq, GPI, RstIF, RstEncs, SetTS, RstEnc1, RstEnc2, Low, High, OutCyc, OutSeq
PIN1=GPI
PIN2=GPI
PIN3=GPI
PIN4=GPI
PIN5=GPI
PIN6=GPI
PIN7=GPI
PIN8=GPI
PIN9=GPI
PIN10=GPI
PIN11=GPI
PIN12=GPI
PIN13=GPI
PIN14=GPI
PIN15=GPI
PIN16=GPI
PIN17=GPI
PIN18=GPI
PIN19=GPI
PIN20=GPI
PIN21=GPI
PIN22=GPI
PIN23=GPI
PIN24=GPI
PIN25=GPI
PIN26=GPI
PIN27=GPI
PIN28=GPI
PIN29=GPI
PIN30=GPI
PIN31=GPI
PIN32=GPI

